SENSITIVE_TAGS = [
    "pussy",
    "pussy peek",
    "clitoris",
    "cervix",
    "penis",
    "pubic hair",
    "anus",
    "nude",
    "completely nude",
    "nipples",
    "precum",
    "cum",
    "ejaculation",
    "sex",
    "fingering",
    "oral",
    "fellatio",
    "irrumatio",
    "cunnilingus",
    "uncensored",
    "scat",
]

VIOLENCE_TAGS = [
    "guro",
    "gore",
    "death",
]

KAOMOJI_TAGS = [
    "0_0",
    "(o)_(o)",
    "+_+",
    "+_-",
    "._.",
    "<o>_<o>",
    "<|>_<|>",
    "=_=",
    ">_<",
    "3_3",
    "6_9",
    ">_o",
    "@_@",
    "^_^",
    "o_o",
    "u_u",
    "x_x",
    "|_|",
    "||_||",
]

ALLOWED_META_TAGS = [
    "lowres",
    "highres",
    "absurdres",
    "incredibly absurdres",
    "cropped",
    "bad aspect ratio",
    "jpeg artifacts",
    "tall image",
    "wide image",
    "ai-generated",
    "ai-assisted",
    "anime screencap",
    "game screenshot",
    "screenshot",
    "eyecatch",
    "end card",
    "game cg",
    "novel illustration",
    "official art",
    "game model",
    "key visual",
    "production art",
    "scan",
    "scan dust",
    "binding discoloration",
    "avatar generator",
]

NSFW_TAG = "nsfw"

DEFAULT_EXLUSION_META_TAGS = ["pixel-perfect_duplicate", "duplicate"]
